#!/usr/bin/env sh
echo '🚀 Husky pre-commit hook is running...'

echo '📝 Formatting Document'
npm run format

echo '🧪 Running tests...'
npm run test -- --passWithNoTests ||
{
    echo '❌ Tests are failing, please review and fix your code before committing';
    exit 1;
}

echo '✨ Checking Prettier standards...'
npm run check-format ||
{
    echo '❌ Bad code styling, please review and fix';
    exit 1;
}

# echo '🔍 Checking ESLint standards...'
# npm run check-lint ||
# {
#     echo '❌ ESLint errors found, please review and fix';
#     exit 1; 
# }

echo '📘 Checking TypeScript types...'
npm run check-types ||
{
    echo '❌ Type check failed. Please fix TypeScript errors.';
    exit 1;
}

# If everything passes... Now we can commit
echo '✅ All checks passed! Committing now...'

